# Generated by Django 5.1.4 on 2025-01-11 21:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nagoyameshi', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='favorite',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ユーザーID'),
        ),
        migrations.AddField(
            model_name='reservations',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ユーザーID'),
        ),
        migrations.AddField(
            model_name='reservations',
            name='restaurant_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Reservations_restaurant_id', to='nagoyameshi.restaurant', verbose_name='店舗ID'),
        ),
        migrations.AddField(
            model_name='favorite',
            name='restaurant_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Favorite_restaurant_id', to='nagoyameshi.restaurant', verbose_name='店舗ID'),
        ),
        migrations.AddField(
            model_name='categoryrestaurant',
            name='restaurants_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nagoyameshi.restaurant', verbose_name='店舗ID'),
        ),
        migrations.AddField(
            model_name='review',
            name='restaurants_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurants_id', to='nagoyameshi.restaurant', verbose_name='店舗ID'),
        ),
        migrations.AddField(
            model_name='review',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ユーザーID'),
        ),
        migrations.AddField(
            model_name='stripecustomer',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ユーザーID'),
        ),
        migrations.AlterUniqueTogether(
            name='favorite',
            unique_together={('user_id', 'restaurant_id')},
        ),
    ]
