# Generated by Django 5.1.4 on 2025-01-17 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nagoyameshi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='seating_capacity',
            field=models.PositiveSmallIntegerField(verbose_name='座席数'),
        ),
    ]
